-- 数据源配置表（兼容 dmp-atelier DMP_DATASOURCE）
CREATE TABLE IF NOT EXISTS DMP_DATASOURCE (
    PK_DATASOURCE VARCHAR(36) PRIMARY KEY,
    PK_DS_CATALOG VARCHAR(36),
    DS_NAME VARCHAR(200),
    DATABASE_NAME VARCHAR(100),
    DB_TYPE VARCHAR(30),
    ENABLE INT DEFAULT 1,
    CONNECT_URL VARCHAR(500),
    DS_USERNAME VARCHAR(200),
    VERIFICATION VARCHAR(500),
    POOL_INITIAL_SIZE INT,
    POOL_MAX_IDLE INT,
    POOL_MAX_ACTIVE INT,
    POOL_MAX_WAIT INT,
    POOL_MIN_IDLE INT,
    CREATE_TIME TIMESTAMP,
    MODIFY_TIME TIMESTAMP
);

-- 元数据表（新表，语义对齐 MetaTableVO）
CREATE TABLE IF NOT EXISTS ATELIER_META_TABLE (
    PK_META_TABLE VARCHAR(36) PRIMARY KEY,
    CATALOG_CODE VARCHAR(100),
    TABLE_CODE VARCHAR(100) NOT NULL,
    TABLE_NAME VARCHAR(200),
    PK_DATASOURCE VARCHAR(36),
    SCHEMA_CODE VARCHAR(100),
    COMMENTS VARCHAR(500),
    CREATE_TIME TIMESTAMP,
    MODIFY_TIME TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ATELIER_META_TABLE_FIELD (
    PK_META_FIELD VARCHAR(36) PRIMARY KEY,
    PK_META_TABLE VARCHAR(36) NOT NULL,
    FIELD_CODE VARCHAR(100) NOT NULL,
    FIELD_NAME VARCHAR(200),
    FIELD_TYPE VARCHAR(50),
    FIELD_LENGTH INT,
    FIELD_PRECISION INT,
    NULLABLE INT,
    SORT_NO INT
);

-- 维度（语义对齐 DMP_STD_K_DIM）
CREATE TABLE IF NOT EXISTS ATELIER_DIMENSION (
    PK_DIMENSION VARCHAR(36) PRIMARY KEY,
    CATALOG_CODE VARCHAR(100),
    DS_CODE VARCHAR(100) NOT NULL,
    DS_NAME VARCHAR(200),
    DS_TYPE VARCHAR(30),
    PK_DATASOURCE VARCHAR(36),
    PK_META_TABLE VARCHAR(36),
    COMMENTS VARCHAR(500),
    CREATE_TIME TIMESTAMP,
    MODIFY_TIME TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ATELIER_DIMENSION_FIELD (
    PK_DIM_FIELD VARCHAR(36) PRIMARY KEY,
    PK_DIMENSION VARCHAR(36) NOT NULL,
    FIELD_CODE VARCHAR(100),
    FIELD_NAME VARCHAR(200),
    FIELD_TYPE VARCHAR(50),
    CODE_FIELD INT,
    NAME_FIELD INT,
    PARENT_FIELD INT,
    SORT_NO INT
);

CREATE TABLE IF NOT EXISTS ATELIER_DIMENSION_VALUE (
    PK_DIM_VALUE VARCHAR(36) PRIMARY KEY,
    PK_DIMENSION VARCHAR(36) NOT NULL,
    CODE VARCHAR(100),
    NAME VARCHAR(200),
    PARENT_CODE VARCHAR(100),
    SORT_NO INT
);

-- 指标定义（声明式 JSON，替代 DMP_ATELIER_N_INDEX 多表）
CREATE TABLE IF NOT EXISTS ATELIER_METRIC_DEFINITION (
    PK_METRIC VARCHAR(36) PRIMARY KEY,
    METRIC_CODE VARCHAR(100) NOT NULL UNIQUE,
    METRIC_NAME VARCHAR(200),
    CATALOG_CODE VARCHAR(100),
    METRIC_TYPE VARCHAR(30),
    PK_DATASOURCE VARCHAR(36),
    DEFINITION_JSON CLOB,
    ENABLED INT DEFAULT 1,
    CREATE_TIME TIMESTAMP,
    MODIFY_TIME TIMESTAMP
);

-- 预警规则（语义对齐 DMP_ATELIER_WARNING_RULE）
CREATE TABLE IF NOT EXISTS ATELIER_WARNING_RULE (
    PK_WARNING_RULE VARCHAR(36) PRIMARY KEY,
    CATALOG_CODE VARCHAR(100),
    RULE_CODE VARCHAR(100) NOT NULL,
    RULE_NAME VARCHAR(200),
    METRIC_CODES VARCHAR(500),
    EXPRESSION VARCHAR(1000),
    ENABLED INT DEFAULT 1,
    WARNING_LEVEL INT,
    NOTIFY_CONFIG CLOB,
    COMMENTS VARCHAR(500),
    CREATE_TIME TIMESTAMP,
    MODIFY_TIME TIMESTAMP
);

-- 演示业务表
CREATE TABLE IF NOT EXISTS dept (
    id VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dept_id VARCHAR(20),
    dept_code VARCHAR(20),
    fiscal_year VARCHAR(10),
    amount DECIMAL(18, 2),
    cost_amount DECIMAL(18, 2)
);
